leo:
  diff_drive:
    type: "diff_drive_controller/DiffDriveController"
    publish_rate: 30
    cmd_vel_timeout: 0.5 # stop after1/2 second of no velo commands
    base_frame_id: "base_root"


    left_wheel: ["left_front_wheel_joint", "left_back_wheel_joint"]
    right_wheel: ["right_front_wheel_joint", "right_back_wheel_joint"]
    pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    # pose_covariance_diagonal: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    # twist_covariance_diagonal: [0.002, 0.02, 0.0, 0.0, 0.0, 0.001]
    enable_odom_tf: false
    odom_frame_id: "odom"

    wheel_radius: 0.15
    wheel_separation: 0.6
    wheel_separation_multiplier: 1.5 # used to be 1.5


    publish_cmd: false
    publish_odom: false 
    allow_multiple_cmd_vel_publishers: true

    linear:
        x:  
            has_velocity_limits    : true
            max_velocity           : 2.0   # m/s
            has_acceleration_limits: true
            max_acceleration       : 5.0  # m/s^2
    angular:
        z:
            has_velocity_limits: true
            max_velocity: 4.0 # rad/s
            has_acceleration_limits: true
            max_acceleration       : 20.0  # rad/s^2

  joint_state_publisher:
    type: "joint_state_controller/JointStateController"
    publish_rate: 10
