TrajectoryPlannerROS:
  controller_frequency: 10.0
  global_frame_id: odom
  
  sim_granularity: 0.005 # half a centimeter steps
  angular_sim_granularity: 0.005 # radians

  yaw_goal_tolerance: 0.15 # radians -- roughly 10 degrees for now
  xy_goal_tolerance: 0.20 # two centimeters
  latch_xy_goal_tolerance: false

  oscillation_reset_dist: 0.30 # 5 centimeters 

  holonomic_robot: false

  max_vel_x: 2.0
  min_vel_x: 0.2
  max_vel_theta: 3.0 # rad/s 
  min_vel_theta: 0.3
  min_in_place_vel_theta: 0.5

  escape_vel: -0.2

  acc_lim_theta: 5.0 
  acc_lim_x: 3.0 

  # http://wiki.ros.org/base_local_planner
  meter_scoring: true
  path_distance_bias: 0.6
  goal_distance_bias: 3.0
  occdist_scale: 0.01
  heading_lookahead: 0.325
  heading_scoring: false
  # heading_scoring_timestep: 0.8 # not used RN 
  dwa: true # dynamic window approach

  publish_cost_grid_pc: false 

  prune_plan: true

