#might need to be set lower for real life
obstacle_range: 11.0
raytrace_range: 12.0

#acceptable delays for tf
transform_tolerance: 0.3

# need to check the order of these!!!!
footprint: [[0.5, 0.25], [0.5, -0.25], [-0.5, -0.25], [-0.5, 0.25]]
footprint_padding: 0.05

inflation_radius: 0.2 # paths will be 0.2 meters away from obstacles
cost_scaling_factor: 100
track_unknown_space: false 

observation_sources: lidar_scan_sensor
# lidar_scan_sensor: {sensor_frame: "lidar", data_type: LaserScan, topic: "lidar/scan", marking: true, clearing: true}
lidar_scan_sensor: {data_type: LaserScan, topic: "lidar/scan", marking: true, clearing: true, inf_is_valid: true}
