

robot_base_frame: base_root
costmap_topic: map
costmap_updates_topic: map_updates
visualize: true
planner_frequency: 1.0
progress_timeout: 20.0
transform_tolerance: 0.3 
min_frontier_size: 1.0

potential_scale: 2.0 
gain_scale: 1.0
