global_costmap:
  global_frame: map
  robot_base_frame: base_root 
  update_frequency: 10
  static_map: false
  rolling_window: true
  
  width: 30.0
  height: 30.0
  resolution: 0.05
  origin_x: 0.0 
  origin_y: 0.0

   
