local_costmap:
  global_frame: odom
  robot_base_frame: base_root
  update_frequency: 5.0
  publish_frequency: 2.0
  static_map: false # true only if using map from disk 
  rolling_window: true 
  width: 12.0
  height: 12.0
  resolution: 0.05
  origin_x: 0.0 
  origin_y: 0.0
