
base_global_planner: "navfn/NavfnROS"
base_local_planner: "base_local_planner/TrajectoryPlannerROS"

# recovery_behaviors: [""]

controller_frequency: 10.0
planner_patience: 10.0
controller_patience: 20.0

recovery_behavior_enabled: false # for now, could potentially be dangerous to humans

conservative_reset_dist: 3.0
